// <auto-generated />
using MiTiendita.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiTiendita.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MiOrganizacion.MiTiendita.Modelos.Producto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CantidadStock")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SKU")
                        .HasColumnType("longtext");

                    b.Property<int>("TiendaID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("TiendaID");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("MiOrganizacion.MiTiendita.Modelos.Tienda", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<bool>("Abierto")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("BalanceCaja")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Tienda");
                });

            modelBuilder.Entity("MiOrganizacion.MiTiendita.Modelos.Producto", b =>
                {
                    b.HasOne("MiOrganizacion.MiTiendita.Modelos.Tienda", "Tienda")
                        .WithMany("Productos")
                        .HasForeignKey("TiendaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("MiOrganizacion.MiTiendita.Modelos.Tienda", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
