// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySQL.Data;

namespace MySQL.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20201106221300_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MySQL.Bandera", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PaisID")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("URL_Bandera")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.HasIndex("PaisID")
                        .IsUnique();

                    b.ToTable("Banderas");
                });

            modelBuilder.Entity("MySQL.Cuidad", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PaisID")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.HasIndex("PaisID");

                    b.ToTable("Cuidades");
                });

            modelBuilder.Entity("MySQL.CuidadUsuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CuidadID")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CuidadID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("CuidadesUsuarios");
                });

            modelBuilder.Entity("MySQL.Pais", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("Habitantes")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("MySQL.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PaisID")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.HasIndex("PaisID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MySQL.Bandera", b =>
                {
                    b.HasOne("MySQL.Pais", "Pais")
                        .WithOne("Bandera")
                        .HasForeignKey("MySQL.Bandera", "PaisID");
                });

            modelBuilder.Entity("MySQL.Cuidad", b =>
                {
                    b.HasOne("MySQL.Pais", "Pais")
                        .WithMany("Cuidades")
                        .HasForeignKey("PaisID");
                });

            modelBuilder.Entity("MySQL.CuidadUsuario", b =>
                {
                    b.HasOne("MySQL.Cuidad", "Cuidad")
                        .WithMany("CuidadesUsuario")
                        .HasForeignKey("CuidadID");

                    b.HasOne("MySQL.Usuario", "Usuario")
                        .WithMany("CuidadesUsuario")
                        .HasForeignKey("UsuarioID");
                });

            modelBuilder.Entity("MySQL.Usuario", b =>
                {
                    b.HasOne("MySQL.Pais", "Pais")
                        .WithMany("Usuarios")
                        .HasForeignKey("PaisID");
                });
#pragma warning restore 612, 618
        }
    }
}
